Feat/compatible with workflows repo
yardinternet/skeleton-package pull request #40
Opened 2024-11-18 10:14 UTC by FreakyWizard

Zie https://github.com/yardinternet/workflows/pull/1

2024-11-18 13:54 UTC, SimonvanWijhe requested changes

2024-11-18 13:54 UTC, SimonvanWijhe commented on .editorconfig
> +# https://github.com/WordPress/wordpress-develop/blob/trunk/.editorconfig
Comment kan weg

2024-11-18 13:54 UTC, SimonvanWijhe commented on .editorconfig
> +# Hard tabs are often rendered inconsistently by different editors and can be harder to work with than spaces.
comment kan weg

2024-11-18 13:54 UTC, SimonvanWijhe commented on .github/workflows/npm-lock-diff.yml
> +  php-cs-fixer:
php-cs-fixer:?

2024-11-18 13:54 UTC, SimonvanWijhe commented on .github/workflows/markdown-linting.yml
> +  phpstan:
phpstan?

2024-11-19 14:24 UTC, SimonvanWijhe commented on .github/workflows/run-tests.yml
> +    secrets: inherit
Zou je hier php, laravel en testbench versions willen mee geven? Ik weet dat ze nu hetzelfde zullen zijn als de defaults in de workflow maar als iemand ooit andere versies wil mee geven hoef je ze alleen aan te passen.

2024-11-19 14:34 UTC, ictbeheer approved these changes

2024-11-19 14:54 UTC, SimonvanWijhe approved these changes
Na aanpassingen akkooord. Ik heb nog wat dingen doorgevoerd in main dus nog even rebasen.

2024-11-19 15:07 UTC, merged